# This doesn't work the way I expected. It does change users, but it doesn't
# update the stored credentials, so I can't do anything with the new user.
# I'll keep it here, but won't use for now.
#
# Current solution: `gh auth login` opening the appropriate browser every time
# I want to update something.

git_protocol: https
aliases:
  personal: "!ln -s -f ~/.config/gh/hosts.personal.yml ~/.config/gh/hosts.yml && ln -s -f ${PERSONAL_GITCONFIG} ~/.gitconfig && gh auth status"
  work: "!ln -s -f ~/.config/gh/hosts.work.yml ~/.config/gh/hosts.yml && ln -s -f ${WORK_GITCONFIG} ~/.gitconfig && gh auth status"
